#starting from node base image
FROM node:18.16.0

#change the working directory
WORKDIR /client

EXPOSE 3000

#copy files
COPY package.json .
COPY yarn.lock .
RUN yarn install --silent

#copy rest of files
COPY . .

#Start the server
CMD ["yarn", "run", "dev"]